### ISSUE TITLE
Adjust column length

### ISSUE THREAD

**Issue by lexum0** [Rezmason/matrix#1]
Hi, I was thinking about adjusting the column length via url also. The only thing I find missing is the columns feel to short, all the same length. And maybe make the length a bit random. Would that be possible?

**Comment by Rezmason** [comment]
Good timing.

I added this yesterday, but forgot to mention it in the README.md till now. "dropLength" is now specifiable in the URL, and accepts any numeric value. While "raindrops" aren't truly random, increasing the drop length seems to vertically space them out.

I hope the shader code that drives the effect is readable, and can be modified if the amount of variation in length in a single column is insufficient.

**Comment by lexum0** [comment]
Nice! 

A value of 2 feels well, but the greater the value the emptier it looks. I think it needs to instantiate more columns. I'll give the code a try to see if I can modify it. Right now the look is great but the screen feels empty, most of the space is "black". Feels like when the movie is starts, the code is "beginning" but stays at that and never goes past that to a state where it's being running for a while.
