### ISSUE TITLE
CRBug/1173575

### ISSUE THREAD

**Issue by BinaryVixen899** [Rezmason/matrix#10]
Getting this in both Chrome 96 and some other version of Firefox. WebGL itself works fine but whenever I try to run this whether it's in Chrome or VSCode Run and Debug (also w/ Chrome) I get an error of "CRBug/1173575 non-JS module filed deprecated". This sounds pretty self explanatory except that I cannot find any import that's trying to import a non JS file.

**Comment by Rezmason** [comment]
What in blue blazes?!

I'll attempt to repro tonight, and I'll also look around for references to this. It sure does sound specific.

**Comment by Rezmason** [comment]
Bug repro'd, based on what I'm seeing in VS Code and what I'm reading online, this is a Chromium bug from within VS Code. Online suggested fixes include recreating your VS Code configuration files and restarting your computer.

That advice isn't exactly reassuring.

My personal recommendation is to not rely on VS Code to run the project in a browser in the first place. 

On a mac, I can turn any folder into a little server like so:

```
cd /path/to/the/folder
python -m SimpleHTTPServer
```

That should host the contents of that folder at `http://localhost:8000` in any browser you like.

I wish I could be more help, but I have very little experience with VS Code myself, and Chrome bugs are too far outside my wheelhouse. 😅 Let me know if I can be any more help.

**Comment by BinaryVixen899** [comment]
Thanks so much! This is incredibly helpful :) I can't believe I didn't think of something like this ^^;
