### ISSUE TITLE
Custom colours?

### ISSUE THREAD

**Issue by tetsujin1979** [Rezmason/matrix#14]
How can the colours of the glyphs and background be customised? 
I've tried changing the backgroundColor value on line 56 of config.js - https://github.com/Rezmason/matrix/blob/a4a0406826c599b44cb77dfe6d05593e0bff017e/js/config.js#L56 - to 9, 9, 9 for a white background, but this changes the font colour to white so I can't see anything!
What else needs to be changed for the glyph colour?

**Comment by Rezmason** [comment]
Sorry for the late reply!

Check out the `paletteEntries` field on the "palimpsest" version:

https://github.com/Rezmason/matrix/blob/a4a0406826c599b44cb77dfe6d05593e0bff017e/js/config.js#L200

See how the "lowest" color is _brighter_ than the "highest" color?

You can imagine that the values in `paletteEntries` are like values in a Photoshop gradient— they have a color, and a number between zero and one that represents where they fall along the spectrum.

![image](https://user-images.githubusercontent.com/1041555/186323043-9d472a86-5526-4097-89f6-3cf148a712e4.png)

So, for instance, if you want a white background with amber glyphs that turn aquamarine, you could try:

```
tetsujin1979: {
	bloomStrength: 0,
	paletteEntries: [
		{ hsl: [0, 1, 1], at: 0.0 },      // red saturated white
		{ hsl: [0.15, 1, 0.4], at: 0.8 }, // amber saturated slightly dark
		{ hsl: [0.5, 1, 0.4], at: 1.0 },  // cyan saturated slightly dark
	],
},
```

Result:

![image](https://user-images.githubusercontent.com/1041555/186324126-85a4d756-50b4-4204-bdc7-4fb42b39a860.png)

I know the options are a bit confusing, hopefully soon I'll have the time to improve things one way or another. Thanks for taking an interest in the project!
