### ISSUE TITLE
Having issues during implementation 

### ISSUE THREAD

**Issue by Devanshukoli** [Rezmason/matrix#20]
I have download the code but troubleing in implementation of this project on my holographic screen . 
Although it's starting but end in 3 sec . 
I have tried buch of things but can't find the answer.

**Comment by Rezmason** [comment]
Sorry for delaying, but I'll need to repair my computer before testing on my hardware.

In the meantime, let's check some stuff:
- When it "ends" in three seconds, does the window turn completely black, or do its graphics just freeze?
- Is your holographic screen a Looking Glass piece of hardware? Do you know its X and Y tile count by any chance?
- Does the problem still happen if you add `&animationSpeed=0` to the URL?
- Does the problem still happen if you instead add `&once=true` to the URL?
- If you remove `version=holoplay` from the URL, does the effect still end after three seconds?

**Comment by Devanshukoli** [comment]
Thanks for reaching out to me and I will check the above stuff you have mentioned. and just got curious so asking if can i do this on a mobile phone (android) as well. Thanks...

**Comment by Devanshukoli** [comment]
Hey, Just let you know I tried your suggestions and it worked!! Thanks .
