### ISSUE TITLE
My issue is there is no issue in rating this the best github repo ever - so there.

### ISSUE THREAD

**Issue by johnoscott** [Rezmason/matrix#23]
Not trying to spam. Just giving high praise. This project is obsessive fandom to the core.

**Comment by Avaray** [comment]
Agree. This repo is awesome.  
My favourite is [Trinity mode](https://rezmason.github.io/matrix?version=trinity) ❤️
I wish to see more Trinity/Morpheus-like modes.

**Comment by Rezmason** [comment]
I'm glad you like those modes, they are brand spanking new!

The "glint" on the glyphs was introduced in the _Resurrections_ opening titles, and while the project has had 3D mode for about a year, Trinity/Morpheus/Bugs mode is only ten days old and they're already making friends. 😁

**Comment by Rezmason** [comment]
Thanks again for the kind words, closing the ticket 😄
