### ISSUE TITLE
glyphs' filenames have forbidden chars

### ISSUE THREAD

**Issue by Kaligula0** [Rezmason/matrix#3]
I can't clone the repo and when I do it manually (ZIP) I can't copy some files:
- `".svg`
- `*.svg`
- `>.svg`
- `<.svg`
- `|.svg`
The chars are forbidden in filenames in Windows.

**Comment by Kaligula0** [comment]
Nevertheless thank you very much for your work! <3

**Comment by Rezmason** [comment]
Sorry, I didn't see this till now! I'll see what I can do about it. Thanks for the compliment!

**Comment by Rezmason** [comment]
I've run the repo through BFG to remove these unnecessary SVG files, along with a couple others. You might need to perform a new git-checkout because of these changes.

Please let me know in a comment if this isn't a complete solution. Cheers!

**Comment by Kaligula0** [comment]
Cloned successfully! <3
