### ISSUE TITLE
Feature Request: 24 fps mode

### ISSUE THREAD

**Issue by bioroid** [Rezmason/matrix#30]
Would like a 24 fps mode to give it that cinematic feel

**Comment by Rezmason** [comment]
Hey which sprint does this go in, @bioroid ? 😆

![image](https://user-images.githubusercontent.com/1041555/193440796-55cbb34d-2545-489c-ac38-c39069d3dbc0.png)

![image](https://user-images.githubusercontent.com/1041555/193440894-c13aac4b-cbbb-4a15-a1cf-e0f30b551818.png)

**Comment by Rezmason** [comment]
Presto!

https://rezmason.github.io/matrix/?fps=24
https://rezmason.github.io/matrix/?fps=12
https://rezmason.github.io/matrix/?fps=1

There was a hidden, tricky aspect to this feature request, which is that the simulation should update at the usual rate while the graphics should update at the specified rate.

The simulation isn't very expensive, but it's important that it runs or the frame skip will affect the state of the cells in strange ways.
