### ISSUE TITLE
Windows screensaver?

### ISSUE THREAD

**Issue by default36** [Rezmason/matrix#31]
Is there a way to make this a screensaver in Windows 10/11?  
Btw this is a dream come true! You're an awesome individual

**Comment by 57r31** [comment]
have you tried Wallpaper Engine?

also there's an interesting app https://github.com/bitrate16/Vebro/
that can take almost any shader from Shadertoy and render it on wallpaper natively

**Comment by Rezmason** [comment]
Thank you! I don't have a Windows machine, and I haven't seen anyone make a Windows screensaver from this yet, but if you can find a Windows screensaver that _displays a web page_, you can install that and point it at the project.

That's your best bet for the foreseeable future; as much as I'm up for the challenge of _programming_ screensavers, the difficulty of supporting software through years of system updates and security policies makes my current project seem like a breeze. Github's doing a lot of the heavy lifting, hosting it and everything! 😄 If I do make any progress on this, though, this repo will reflect it.

**Comment by Rezmason** [comment]
@default36 Issue #12 also tracks this, and it looks like some folks are trying various solutions 🤞
