### ISSUE TITLE
Trans and Pride flag color modes borked

### ISSUE THREAD

**Issue by Vinidia** [Rezmason/matrix#32]
What the title says. The rain just never initiates, sitting at black screen. All other effects work.

**Comment by Rezmason** [comment]
Aw, this _just broke_. Hang tight, I'm on it.

**Comment by Rezmason** [comment]
@Vinidia Thanks for reporting this so quickly! Should be working properly now:

https://rezmason.github.io/matrix/?effect=pride
https://rezmason.github.io/matrix/?effect=trans
