### ISSUE TITLE
skipOutro

### ISSUE THREAD

**Issue by vsevolod-mineev** [Rezmason/matrix#35]
I really really want to make this into a perfectly looping video but "loops" as is pointed out in the documentation is a work in progress (WIP).

To this effect, could you please please implement skipOutro function that has the rain die down in intensity before stopping completely.

I can then finally have my perfectly looping video which I plan to use as a background on a lot of my devices.

Kindest regards,
Vsevolod Mineev

**Comment by Rezmason** [comment]
I think what would be better is if I actually finish implementing the ability to loop the animation. 😅 I'll write that as a separate ticket.
