### ISSUE TITLE
Image displays upside-down with effect=image

### ISSUE THREAD

**Issue by jesse-mend** [Rezmason/matrix#37]
I'm experimenting with a screensaver for my work machine which displays the effect over my company logo. Everything is working great, except that the image displays upside-down for some reason! I checked the demo image (Eagle rock) and discovered that this is true there, too.

To reproduce: effect=image&url=[someUrl]

**Comment by Rezmason** [comment]
D'oh! 🤦 Thank you!

**Comment by Rezmason** [comment]
Oh actually I'll flip the uv in the shader so the REGL and WebGPU renderers are more similar, which was what led me to remove the flipY in the first place

**Comment by Rezmason** [comment]
Spent some time poking around, and I decided I'll try to flipY in REGL _and_ in WebGPU.

Future updates to the project may reveal that my existing code hides some coordinate system differences, but that can't hold up this bugfix!

**Comment by Rezmason** [comment]
Fixed!

A bunch of stuff had been broken by that "removing flipY" commit, oops. Now the WebGPU and REGL projects are both in a better spot. Thanks for reporting the issue!

**Comment by jesse-mend** [comment]
Woot! Sure thing! Thanks for investigating & fixing! 😃
