### ISSUE TITLE
Request : ability to change every setting

### ISSUE THREAD

**Issue by K0wp3R** [Rezmason/matrix#45]
this thing is great, works great, and is very customisable, but i feel like it's sad to not have access to settings like ripples / ripples type in the customisations.
This matrix rain has so much potential, and is the ONLY accurate one i've found (and i have looked for quite a long time) but yeah it could become a lot better if one were to be able to access every setting like the current customisations 
(maybe i'm just stupid and can't figure out how to do it, but i've tried changing the default parameters in the web view, putting stuff like rippleName=circle in the link, like the rest of the parameters with no success)

**Comment by Rezmason** [comment]
Thank you for your kind words and interest in the project!

The work you describe will be a part of a larger initiative to create a GUI that exposes all these settings, changes them (on the fly when possible) and then encodes the result back in the URL. See #9 and #36 .

In the meantime, you're free to download or fork the project and create your own variation in the config file. It's not ideal, but it may hold you over while the GUI work is incomplete.
