### ISSUE TITLE
Feature Request: support Spout or NDI output

### ISSUE THREAD

**Issue by Mankeysocks** [Rezmason/matrix#48]
Could you add Spout or NDI output so we could use this in VJ software?

**Comment by Rezmason** [comment]
Sorry for the slow reply! I don't know anything about the VJing software stack— other than that VJing is really cool— but it looks like most folks who try to do this use something called NDI ScanConverter.

That said, if there's a website that already supports Spout or NDI output somehow, let me know so I can learn more about it.

If you get something working, will you let me know? It sounds like a useful thing to add to the upcoming Examples page.
