### ISSUE TITLE
Change default version

### ISSUE THREAD

**Issue by kopisusugula** [Rezmason/matrix#50]
hi, i wanna ask how to change the default version (classic) display to another version. 
wanna doi it because dont wanna change or access the "version" address on the link.

Thanks.

**Comment by 57r31** [comment]
you can just fork the project and make any defaut settings you wish - that's open source way.

**Comment by Rezmason** [comment]
Seconded! Specifically, [this line](https://github.com/Rezmason/matrix/blob/master/js/config.js#L549) can have `versions.classic` changed to whichever version you prefer to be the default, including something you make yourself. 😊
