### ISSUE TITLE
Set as Windows Terminal background

### ISSUE THREAD

**Issue by golosovsky** [Rezmason/matrix#51]
Any recommendations regarding how to make that a Windows Terminal background? 😅
I have attempted to do it manually – just to experiment with its appearance – by adjusting the Terminal background opacity to 0, and it looks awesome IMO:
![image](https://github.com/Rezmason/matrix/assets/5933207/a37bb648-afe8-468d-a21c-cd79910fdcc5)

PS
Plz don't judge me

**Comment by Rezmason** [comment]
Looks good! Sadly I have no useful suggestions for closer integration.
