### ISSUE TITLE
Missing "6" character in custom font

### ISSUE THREAD

**Issue by jcubic** [Rezmason/matrix#52]
I use your awesome custom Matrix font with my minimalistic [matrix rain effect](https://github.com/jcubic/cmatrix) (a demo with a custom font).

And I'm not sure if you're aware but the font is missing the character "6". I'm not sure if this is intentional but I just decided to create an issue so you're aware of it.

**Comment by Rezmason** [comment]
Thank you, fellow code rain person, for your interest and kind words! I like your project! And _welcome_— to that rarefied fraternity of Matrix fans who notice that the "font", until 2021, is missing a digit. 😄 

To me the lack of a six helps to emphasize that in the movies, the script isn't a notation or a symbolic structure of any kind, it is a **cipher**; any meaning in the scrambled glyphs is intentionally hidden layers deep from those who seek knowledge and truth. Including me and you. That's my personal interpretation, of course.

The downside to this interpretation is, anyone who asks me to "put their text in the code" faces a direct obstacle that my glyphs are not text. Most projects such as yours avoid this problem entirely. 😃

That said, when the franchise revisited the glyph set for the fourth film, they asked the multifaceted [Andrew Glass](https://artsci.washington.edu/news/2022-01/ancient-languages-new-technology), Unicode extraordinaire / asian scripts megascholar / repeat Matrix franchise advisor, to expand it, and he took a more informed approach:

> As you noted, the digit 6 seems to have been omitted from the trilogy set. It seemed to me that there should be a complete numbering system, so a six would have been required. Let's imagine one might pick from the new signs, sufficient symbols to complete a hexadecimal set. Also, punctuation and common symbols might be needed in this "language", so maybe basic ASCII punctuation should have been included as a source too.

To me this is very fitting in light of the advances to the world depicted in _Resurrections_: the simulation is more devious; human and synthetic life live side-by-side in IO; and surprisingly, Neo is depicted as voluntarily using the original Matrix code for software development.

You get used to it, though. Your brain does the translating. I bet he doesn't even see the code. All he sees is Vue, React, and Svelte.

Matrix has ya!

-Rezmason



PS— thank you for [being a teacher](https://koduj.org/)! 📚
