### ISSUE TITLE
Custom fonts and symbols

### ISSUE THREAD

**Issue by polynomm** [Rezmason/matrix#56]
Is it possible to add a guide step by step in markdown, or a tool to add custom fonts and symbols locally?

Even if it's not possible to put characters directly as a string associated with a font (for example: localFont="Futura", unicodeGlyphs="AaBb...?+&_$#@"), it could be interesting to select a set of glyphs, and make the necessary files (svg and png images) with clear instructions to add that set as a font option.

**Comment by Rezmason** [comment]
Sorry for the late reply,

Currently there are instructions in [this closed issue](https://github.com/Rezmason/matrix/issues/4) 😅 I'll be making examples soon, and this will be one of the more advanced ones. Rest assured it's on a to-do list.
